
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.

(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))

;; (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
;;                          ("marmalade" . "https://marmalade-repo.org/packages/")
;;                          ("melpa" . "https://melpa.org/packages/")))

(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents))

(defvar myPackages
  '(flatui-theme
    better-defaults
    ein
    elpy
    jedi
    flycheck
    py-autopep8
    direx
    direx-grep
    pylint
    ace-window
    magit
    ecb
    langtool))

(mapc #'(lambda (package)
          (unless (package-installed-p package)
            (package-install package)))
      myPackages)

;; BASIC CUSTOMIZATION
;; --------------------------------------

(setq column-number-mode t)

(setq inhibit-startup-message t) ;; hide the startup message
;; (load-theme 'flatui t) ;; load material theme
(global-linum-mode t) ;; enable line numbers globally

(require 'ido)
(ido-mode t)

(require 'ispell)
(require 'flyspell)
(add-hook 'python-mode-hook 'flyspell-prog-mode)

;; ace-window
(global-set-key (kbd "C-x o") 'ace-window)

;; DIREX
(require 'direx)
(global-set-key (kbd "C-x C-j") 'direx:jump-to-directory)


;; PYTHON CONFIGURATION ---------------------------------------
;; python and elpy
(elpy-enable)


;; python with flycheck
(when (require 'flycheck nil t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
    (add-hook 'elpy-mode-hook 'flycheck-mode))

;; py-autopep8
(require 'py-autopep8)
(add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

;; jedi setup
;; (add-hook 'python-mode-hook 'jedi:setup)

;; environment speciifc
;; setting  up, activating virtualenv
;; (require 'pyvenv)
;; (pyvenv-activate "~/env/virtualenv/")

;; fill-paragraph set to 80
(setq-default fill-column 80)

;; column markers
;; (require 'column-marker)
;; (add-hook 'find-file-hook (lambda () (interactive) (column-marker-1 80)))
;; (add-hook 'find-file-hook (lambda () (interactive) (column-marker-2 78)))
;; (add-hook 'find-file-hook (lambda () (interactive) (column-marker-3 75)))

;; configure direx-grep
(require 'direx-grep)
(define-key direx:direx-mode-map (kbd "s") 'direx-grep:grep-item)
(define-key direx:direx-mode-map (kbd "S") 'direx-grep:grep-item-from-root)
(define-key direx:direx-mode-map (kbd "a") 'direx-grep:show-all-item-at-point)
(define-key direx:direx-mode-map (kbd "A") 'direx-grep:show-all-item)

;; increase the size of text across all buffers, in all modes.


;; setting up langtool that points to a languagetool-commandling.jre
(require 'langtool)
(setq langtool-language-tool-jar "/home/dominik/sources/langtool/LanguageTool-3.9/languagetool-commandline.jar")
(setq langtool-mother-tongue "en")

;; setting up flyspell and ispell for text-mode
(add-hook 'text-mode-hook 'flyspell-mode)
(setq ispell-dictionary "british"
      ispell-extra-args '() ;; TeX mode "-t"
      ispell-silently-savep t)




;; ============================================================================
;; init.el ENDS HERE! The code below has been generated by emacs.
;; ============================================================================

